title: "Around the Island (ATI) — Moorea- French Polynesia - 16S rRNA gene Project"
description: "Environmental DNA (eDNA) microbial community analyses around Moorea, French Polynesia"
theme: jekyll-theme-cayman
show_downloads: false
google_analytics: false
