title: "Around the Island (ATI) — Moorea Island, French Polynesia - 16S rRNA gene Project"
description: "Environmental DNA (eDNA) microbial community analyses around Moorea Island, French Polynesia"
plugins:
  - jekyll-remote-theme
remote_theme: slashben/jekyll-theme-jellyfish
show_downloads: false

header_pages:
  - index.md
  - Methods/imdex.md
  - Pipeline/index.md
  - Code/index.md
  - Data/index.md
  - Figures/index.md
