---
title: "Spatial regression of log abundances"
format: 
  html:
    self-contained: true
editor: source
editor_options: 
  chunk_output_type: console
---

## Data prep

```{r data, warning=F, message=F}
#| code-fold: true

library(phyloseq)
library(ggplot2)
library(RColorBrewer)
library(stringr)
library(tidyr)
library(dplyr)
library(spmodel)
library(sf)

level <- 'family'; level2 <- 'Family'

physeq_rrfy <- 
  readr::read_rds(paste0('../data/ati-physeq-rrfy-', level2, '.rds')) %>% 
  #transform_sample_counts(function(x) (x / sum(x))*100) %>% 
  subset_taxa(Family == "Vibrionaceae" | 
                Family == "Nitrincolaceae" | 
                Family == "Pseudoalteromonadaceae" | 
                Family == "Moraxellaceae" |
                Family == "Halomonadaceae")

taxa <- tax_table(physeq_rrfy)@.Data %>% 
  data.frame() %>% 
  dplyr::mutate(asv = row.names(.)) %>% 
  dplyr::select(asv, Family)

abundances <- 
  phyloseq::sample_data(physeq_rrfy) %>% 
  as_tibble() %>% 
  dplyr::select(Site, Latitude, Longitude, Year, Habitat, Island_shore,
                Silicate, Percent_N, Phosphate, Ammonia, Nitrite_plus_Nitrate,
                Distance_to_shore, Distance_to_population_center,
                dN15, dC13) %>%
  dplyr::mutate(Site = as.factor(Site),
                Year = as.factor(Year),
                Habitat = factor(Habitat,
                                    levels = c('Mid lagoon','Fringing reef','Bay','Reef crest','Reef pass'))) %>% 
  bind_cols(
    phyloseq::otu_table(physeq_rrfy) %>% 
      t()) %>% 
  na.omit() %>% 
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>% 
  st_transform(crs = 3305)

# Verify taxa names and order
#colnames(abundances)[4:ncol(abundances)] 
colnames(abundances)[grep(paste(taxa$asv, collapse = "|"),
                          colnames(abundances))] <- taxa$Family
```

## Model and plot log abundances of top families

```{r model_plot, warning=F, message=F, eval=T}
#| code-fold: true

#Geospatial layers:
bbox <- st_bbox(abundances)
moorea <- st_read('../data/map-data/moorea.shp', quiet=TRUE)

#set theme parameters
mytheme <- theme(legend.position="bottom",
                 axis.title.x = element_blank(),
                 axis.title.y = element_blank(),
                 legend.text=element_text(size=12),
                 legend.title=element_text(size=12)) 

taxa <- taxa$Family
predictors <- 'Habitat + Year + Silicate + Percent_N + Phosphate + Ammonia + Nitrite_plus_Nitrate + Distance_to_shore + Distance_to_population_center + dN15 + dC13' 

for(i in 1:length(taxa)){
  #for(i in 1:1){
  print(taxa[i])
  
  map <-   ggplot() +
    geom_sf(data=moorea, fill='white', color='black') +
    geom_sf(data=abundances, aes(color=.data[[taxa[i]]]+1), size=3, alpha=1) +
    theme_bw() +
    mytheme + 
    scale_color_distiller(palette='GnBu', taxa[i], direction = 1, trans = "log10") +
    guides(color = guide_colourbar(barwidth = 15)) +
    facet_wrap(~Year, ncol = 3)
  print(map)
  
  taxon <- paste0("`", taxa[i], "`")  # Wrap in backticks
  formula <- as.formula(paste("log10(", taxon, " + 1) ~", predictors))
  
  mod <- splm(formula = formula,
              data = abundances,
              random = ~ Site,
              estmethod='ml',
              spcov_type = 'none')
  
  sp.mod <- splm(formula = formula, 
                 data = abundances,
                 #partition_factor = ~ Island_shore,
                 random = ~ Site,
                 estmethod='ml',
                 spcov_type = 'gaussian') 
  
  print('Compare spatial and non-spatial models')
  glances(mod, sp.mod) %>% print()
  
  print('Leave-one-out assessment')
  bind_rows(
    loocv(mod) %>% mutate(Model = "non-spatial"),
    loocv(sp.mod) %>% mutate(Model = "spatial")
  ) %>% print()
  
  sp.mod <- splm(formula = formula, 
                 data = abundances,
                 #partition_factor = ~ Island_shore,
                 random = ~ Site,
                 #estmethod='ml',
                 spcov_type = 'gaussian') 
  
  print(summary(sp.mod))
  
}

```
